//
// Module ReadOutControl_lib.fifo.struct
//
// Created:
//          by - jds.UNKNOWN (ANDOORN)
//          at - 14:22:23  4-08-2009
//
// Generated by Mentor Graphics' HDL Designer(TM) 2008.1 (Build 17)
//

`resetall
`timescale 1ns/10ps
module fifo( 
   rclk, 
   rinc, 
   rrst_n, 
   wclk, 
   wdata, 
   winc, 
   wrst_n, 
   rdata, 
   rempty, 
   wfull
);


// Internal Declarations

input          rclk;
input          rinc;
input          rrst_n;
input          wclk;
input   [35:0] wdata;
input          winc;
input          wrst_n;
output  [35:0] rdata;
output         rempty;
output         wfull;


wire         rclk;
wire         rinc;
wire         rrst_n;
wire         wclk;
wire  [35:0] wdata;
wire         winc;
wire         wrst_n;
wire  [35:0] rdata;
wire         rempty;
wire         wfull;

// Local declarations

// Internal signal declarations
wire  [2:0] raddr;
wire  [3:0] rptr;
wire  [3:0] rq2_wptr;
wire  [2:0] waddr;
wire  [3:0] wptr;
wire  [3:0] wq2_rptr;


// Instances 
fifomem U_0( 
   .rdata  (rdata), 
   .wdata  (wdata), 
   .waddr  (waddr), 
   .raddr  (raddr), 
   .wclken (winc), 
   .wfull  (wfull), 
   .wclk   (wclk)
); 

rptr_empty_seu U_1( 
   .rempty   (rempty), 
   .raddr    (raddr), 
   .rptr     (rptr), 
   .rq2_wptr (rq2_wptr), 
   .rinc     (rinc), 
   .rclk     (rclk), 
   .rrst_n   (rrst_n)
); 

sync_r2w U_2( 
   .wq2_rptr (wq2_rptr), 
   .rptr     (rptr), 
   .wclk     (wclk), 
   .wrst_n   (wrst_n)
); 

sync_w2r U_3( 
   .rq2_wptr (rq2_wptr), 
   .wptr     (wptr), 
   .rclk     (rclk), 
   .rrst_n   (rrst_n)
); 

wptr_full_seu U_5( 
   .wfull    (wfull), 
   .waddr    (waddr), 
   .wptr     (wptr), 
   .wq2_rptr (wq2_rptr), 
   .winc     (winc), 
   .wclk     (wclk), 
   .wrst_n   (wrst_n)
); 


endmodule // fifo

