//
// Module ReadOutControl_lib.Formatter_data.struct
//
// Created:
//          by - jds.UNKNOWN (ANDOORN)
//          at - 12:42:06 04/ 7/2010
//
// Generated by Mentor Graphics' HDL Designer(TM) 2008.1 (Build 17)
//

`resetall
`timescale 1ns/10ps
module Formatter_data( 
   ColumnHamm, 
   DataHamm, 
   ReadyIn, 
   Reset, 
   RowHamm, 
   TriggerFinishIn, 
   WriteIn, 
   clk, 
   DataOut_Column, 
   DataOut_Row, 
   DataOut_TotBottom, 
   DataOut_TotTop, 
   ReadyOut, 
   WriteOut
);


// Internal Declarations

input   [9:0]  ColumnHamm;
input   [24:0] DataHamm;
input          ReadyIn;
input          Reset;
input   [11:0] RowHamm;
input          TriggerFinishIn;
input          WriteIn;
input          clk;
output  [6:0]  DataOut_Column;
output  [8:0]  DataOut_Row;
output  [3:0]  DataOut_TotBottom;
output  [3:0]  DataOut_TotTop;
output         ReadyOut;
output         WriteOut;


wire  [9:0]  ColumnHamm;
wire  [24:0] DataHamm;
wire         ReadyIn;
wire         Reset;
wire  [11:0] RowHamm;
wire         TriggerFinishIn;
wire         WriteIn;
wire         clk;
wire  [6:0]  DataOut_Column;
wire  [8:0]  DataOut_Row;
wire  [3:0]  DataOut_TotBottom;
wire  [3:0]  DataOut_TotTop;
wire         ReadyOut;
wire         WriteOut;

// Local declarations

// Internal signal declarations
wire        DataMemIn_DataLeft_NeiB;
wire        DataMemIn_DataLeft_NeiT;
wire  [3:0] DataMemIn_DataLeft_TotB;
wire  [3:0] DataMemIn_DataLeft_TotT;
wire        DataMemIn_DataRight_NeiB;
wire        DataMemIn_DataRight_NeiT;
wire  [3:0] DataMemIn_DataRight_TotB;
wire  [3:0] DataMemIn_DataRight_TotT;
wire        DataMemOut_DataLeft_NeiB;
wire        DataMemOut_DataLeft_NeiT;
wire  [3:0] DataMemOut_DataLeft_TotB;
wire  [3:0] DataMemOut_DataLeft_TotT;
wire        DataMemOut_DataRight_NeiB;
wire        DataMemOut_DataRight_NeiT;
wire  [3:0] DataMemOut_DataRight_TotB;
wire  [3:0] DataMemOut_DataRight_TotT;
wire        DataSaveBottomLeft_NeiB;
wire        DataSaveBottomLeft_NeiT;
wire  [3:0] DataSaveBottomLeft_TotB;
wire  [3:0] DataSaveBottomLeft_TotT;
wire        DataSaveBottomRight_NeiB;
wire        DataSaveBottomRight_NeiT;
wire  [3:0] DataSaveBottomRight_TotB;
wire  [3:0] DataSaveBottomRight_TotT;
wire        DataSaveTopLeft_NeiB;
wire  [3:0] DataSaveTopLeft_TotB;
wire        DataSaveTopRight_NeiB;
wire  [3:0] DataSaveTopRight_TotB;
wire        NeedMoreWriteLeft;
wire        NeedMoreWriteRight;
wire        NeiRegions;
wire        OutLeft_NeiB;
wire        OutLeft_NeiT;
wire  [3:0] OutLeft_TotB;
wire  [3:0] OutLeft_TotT;
wire        OutRight_NeiB;
wire        OutRight_NeiT;
wire  [3:0] OutRight_TotB;
wire  [3:0] OutRight_TotT;
wire  [2:0] PositionLeft;
wire  [2:0] PositionRight;
wire  [3:0] TotBottomLeft;
wire  [3:0] TotBottomRight;
wire  [3:0] TotTopLeft;
wire  [3:0] TotTopRight;
wire  [5:0] out;
wire  [7:0] out1;


// Instances 
DataFormatterTriple U_6( 
   .clk                       (clk), 
   .Reset                     (Reset), 
   .WriteIn                   (WriteIn), 
   .TriggerFinishIn           (TriggerFinishIn), 
   .ReadyIn                   (ReadyIn), 
   .ColumnIn                  (out), 
   .RowIn                     (out1), 
   .WriteOut                  (WriteOut), 
   .ReadyOut                  (ReadyOut), 
   .DataOut_Column            (DataOut_Column), 
   .DataOut_Row               (DataOut_Row), 
   .DataOut_TotTop            (DataOut_TotTop), 
   .DataOut_TotBottom         (DataOut_TotBottom), 
   .PositionLeft              (PositionLeft), 
   .PositionRight             (PositionRight), 
   .DataLeftIn_NeiT           (OutLeft_NeiT), 
   .DataLeftIn_NeiB           (OutLeft_NeiB), 
   .DataLeftIn_TotT           (OutLeft_TotT), 
   .DataLeftIn_TotB           (OutLeft_TotB), 
   .DataRightIn_NeiT          (OutRight_NeiT), 
   .DataRightIn_NeiB          (OutRight_NeiB), 
   .DataRightIn_TotT          (OutRight_TotT), 
   .DataRightIn_TotB          (OutRight_TotB), 
   .DataSaveTopLeft_NeiB      (DataSaveTopLeft_NeiB), 
   .DataSaveTopLeft_TotB      (DataSaveTopLeft_TotB), 
   .DataSaveTopRight_NeiB     (DataSaveTopRight_NeiB), 
   .DataSaveTopRight_TotB     (DataSaveTopRight_TotB), 
   .DataSaveBottomLeft_NeiT   (DataSaveBottomLeft_NeiT), 
   .DataSaveBottomLeft_NeiB   (DataSaveBottomLeft_NeiB), 
   .DataSaveBottomLeft_TotT   (DataSaveBottomLeft_TotT), 
   .DataSaveBottomLeft_TotB   (DataSaveBottomLeft_TotB), 
   .DataSaveBottomRight_NeiT  (DataSaveBottomRight_NeiT), 
   .DataSaveBottomRight_NeiB  (DataSaveBottomRight_NeiB), 
   .DataSaveBottomRight_TotT  (DataSaveBottomRight_TotT), 
   .DataSaveBottomRight_TotB  (DataSaveBottomRight_TotB), 
   .DataMemIn_DataLeft_NeiT   (DataMemIn_DataLeft_NeiT), 
   .DataMemIn_DataLeft_NeiB   (DataMemIn_DataLeft_NeiB), 
   .DataMemIn_DataLeft_TotT   (DataMemIn_DataLeft_TotT), 
   .DataMemIn_DataLeft_TotB   (DataMemIn_DataLeft_TotB), 
   .DataMemIn_DataRight_NeiT  (DataMemIn_DataRight_NeiT), 
   .DataMemIn_DataRight_NeiB  (DataMemIn_DataRight_NeiB), 
   .DataMemIn_DataRight_TotT  (DataMemIn_DataRight_TotT), 
   .DataMemIn_DataRight_TotB  (DataMemIn_DataRight_TotB), 
   .DataMemOut_DataLeft_NeiT  (DataMemOut_DataLeft_NeiT), 
   .DataMemOut_DataLeft_NeiB  (DataMemOut_DataLeft_NeiB), 
   .DataMemOut_DataLeft_TotT  (DataMemOut_DataLeft_TotT), 
   .DataMemOut_DataLeft_TotB  (DataMemOut_DataLeft_TotB), 
   .DataMemOut_DataRight_NeiT (DataMemOut_DataRight_NeiT), 
   .DataMemOut_DataRight_NeiB (DataMemOut_DataRight_NeiB), 
   .DataMemOut_DataRight_TotT (DataMemOut_DataRight_TotT), 
   .DataMemOut_DataRight_TotB (DataMemOut_DataRight_TotB), 
   .TotTopLeft                (TotTopLeft), 
   .TotBottomLeft             (TotBottomLeft), 
   .TotTopRight               (TotTopRight), 
   .TotBottomRight            (TotBottomRight), 
   .NeedMoreWriteLeft         (NeedMoreWriteLeft), 
   .NeedMoreWriteRight        (NeedMoreWriteRight), 
   .NeiRegions                (NeiRegions)
); 

column_hamming_dec U_1( 
   .in  (ColumnHamm), 
   .out (out)
); 

data_hamming_dec U_0( 
   .in            (DataHamm), 
   .OutLeft_NeiT  (OutLeft_NeiT), 
   .OutLeft_NeiB  (OutLeft_NeiB), 
   .OutLeft_TotT  (OutLeft_TotT), 
   .OutLeft_TotB  (OutLeft_TotB), 
   .OutRight_NeiT (OutRight_NeiT), 
   .OutRight_NeiB (OutRight_NeiB), 
   .OutRight_TotT (OutRight_TotT), 
   .OutRight_TotB (OutRight_TotB)
); 

pairing_recognition U_4( 
   .DataInTop_NeiT        (DataMemOut_DataLeft_NeiT), 
   .DataInTop_NeiB        (DataMemOut_DataLeft_NeiB), 
   .DataInTop_TotT        (DataMemOut_DataLeft_TotT), 
   .DataInTop_TotB        (DataMemOut_DataLeft_TotB), 
   .DataInBottom_NeiT     (DataMemIn_DataLeft_NeiT), 
   .DataInBottom_NeiB     (DataMemIn_DataLeft_NeiB), 
   .DataInBottom_TotT     (DataMemIn_DataLeft_TotT), 
   .DataInBottom_TotB     (DataMemIn_DataLeft_TotB), 
   .TotTop                (TotTopLeft), 
   .TotBottom             (TotBottomLeft), 
   .DataTopToSave_NeiB    (DataSaveTopLeft_NeiB), 
   .DataTopToSave_TotB    (DataSaveTopLeft_TotB), 
   .DataBottomToSave_NeiT (DataSaveBottomLeft_NeiT), 
   .DataBottomToSave_NeiB (DataSaveBottomLeft_NeiB), 
   .DataBottomToSave_TotT (DataSaveBottomLeft_TotT), 
   .DataBottomToSave_TotB (DataSaveBottomLeft_TotB), 
   .NeedMoreWrite         (NeedMoreWriteLeft), 
   .Position              (PositionLeft), 
   .NeiRegions            (NeiRegions)
); 

pairing_recognition U_5( 
   .DataInTop_NeiT        (DataMemOut_DataRight_NeiT), 
   .DataInTop_NeiB        (DataMemOut_DataRight_NeiB), 
   .DataInTop_TotT        (DataMemOut_DataRight_TotT), 
   .DataInTop_TotB        (DataMemOut_DataRight_TotB), 
   .DataInBottom_NeiT     (DataMemIn_DataRight_NeiT), 
   .DataInBottom_NeiB     (DataMemIn_DataRight_NeiB), 
   .DataInBottom_TotT     (DataMemIn_DataRight_TotT), 
   .DataInBottom_TotB     (DataMemIn_DataRight_TotB), 
   .TotTop                (TotTopRight), 
   .TotBottom             (TotBottomRight), 
   .DataTopToSave_NeiB    (DataSaveTopRight_NeiB), 
   .DataTopToSave_TotB    (DataSaveTopRight_TotB), 
   .DataBottomToSave_NeiT (DataSaveBottomRight_NeiT), 
   .DataBottomToSave_NeiB (DataSaveBottomRight_NeiB), 
   .DataBottomToSave_TotT (DataSaveBottomRight_TotT), 
   .DataBottomToSave_TotB (DataSaveBottomRight_TotB), 
   .NeedMoreWrite         (NeedMoreWriteRight), 
   .Position              (PositionRight), 
   .NeiRegions            (NeiRegions)
); 

row_hamming_dec U_2( 
   .in  (RowHamm), 
   .out (out1)
); 


endmodule // Formatter_data

