//
// Test Bench Module FEI4_A_lib.FEI4_A_top_WrReg_tb.FEI4_A_top_tester
//
// Created:
//          by - Laura.UNKNOWN (SILAB51)
//          at - 17:17:04 01/14/2010
//
// Generated by Mentor Graphics' HDL Designer(TM) 2008.1b (Build 7)
//
`resetall
`timescale 1ns/10ps

module FEI4_A_top_WrReg_tb;

// Inputs
reg [2:0] ChipId;
reg       Ext_Trigger;
reg       DCI;
reg       clk40M;
reg       reset;

//Outputs
wire [15:0] data_out;

//Instantiate Unit Under test
FEI4_A_top U_0(
   .ChipId      (ChipId),
   .Ext_Trigger (Ext_Trigger),
   .DCI         (DCI),
   .clk40M      (clk40M),
   .reset       (reset),
   .data_out    (data_out)
);

//ChipId
initial begin
  ChipId = 0;
end

//Ext_Trigger
initial begin
  Ext_Trigger = 0;
end

//CK
parameter PERIOD = 20;

initial begin
  clk40M = 1'b0;
  #(PERIOD/2);
  forever
    #(PERIOD/2) clk40M = ~clk40M;
end

//reset
initial begin
  reset = 1;
  #10;
  reset = 0;
  #20;
  reset = 1;
end

//DCI    
initial begin
  #40;
  //field 1
  DCI = 1;
  #20;
  DCI = 0;
  #20;
  DCI = 1;
  #20;
  DCI = 1;
  #20;
  DCI = 0;
  //field 2
  #20;
  DCI = 1;
  #20;
  DCI = 0;    
  #20;
  DCI = 0;       
  #20;
  DCI = 0;   
  //field 3
  #20;
  DCI = 0;
  #20;
  DCI = 0;    
  #20;
  DCI = 1;       
  #20;
  DCI = 0;   
  //field 4
  #20;
  DCI = 0;
  #20;
  DCI = 0;    
  #20;
  DCI = 0;       
  #20;
  DCI = 0;   
  //field 5
  #20;
  DCI = 0;       
  #20;
  DCI = 0;   
  #20;
  DCI = 0;
  #20;
  DCI = 0;    
  #20;
  DCI = 1;       
  #20;
  DCI = 1;  
  //field 6
  #20;
  DCI = 0;       
  #20;
  DCI = 0;   
  #20;
  DCI = 0;
  #20;
  DCI = 1;    
  #20;
  DCI = 1;       
  #20;
  DCI = 0;   
  #20;
  DCI = 0;
  #20;
  DCI = 0;    
  #20;
  DCI = 1;       
  #20;
  DCI = 1;   
  #20;
  DCI = 1;       
  #20;
  DCI = 0;   
  #20;
  DCI = 1;
  #20;
  DCI = 0;    
  #20;
  DCI = 1;       
  #20;
  DCI = 0;  
end  
endmodule // FEI4_A_top_WrReg_tb


