//
// Test Bench Module FEI4_A2_lib.FEI4_A_top_tb.FEI4_A_top_tester
//
// Created:
//          by - Laura.UNKNOWN (SILAB51)
//          at - 11:57:35 03/ 1/2010
//
// Generated by Mentor Graphics' HDL Designer(TM) 2008.1b (Build 7)
//
`resetall
`timescale 1ns/10ps

module FEI4_A_top_tb;

// Local declarations

// Internal signal declarations
reg RST_pin;
reg ChipID0;
reg ChipID1;
reg ChipID2;
wire IO_DataIN_CLK_N_pin;
reg IO_DataIN_CLK_P_pin;
reg IO_DataIN_N_pin;
reg IO_DataIN_P_pin;

wire IO_DataOUT1_N_pin;
wire IO_DataOUT1_P_pin;
wire IO_DataOUT2_P_pin;
wire IO_DataOUT2_N_pin;
wire LED_pin;

FEI4_A_top U_0(
   .RST_pin(RST_pin),
   .LED_pin(LED_pin),
   .ChipID0(ChipID0),
   .ChipID1(ChipID1),
   .ChipID2(ChipID2),
   .IO_DataIN_CLK_N_pin (IO_DataIN_CLK_N_pin),
   .IO_DataIN_CLK_P_pin (IO_DataIN_CLK_P_pin),
   .IO_DataIN_N_pin     (IO_DataIN_N_pin),
   .IO_DataIN_P_pin     (IO_DataIN_P_pin),
   .IO_DataOUT1_N_pin   (IO_DataOUT1_N_pin),
   .IO_DataOUT1_P_pin   (IO_DataOUT1_P_pin),
   .IO_DataOUT2_P_pin   (IO_DataOUT2_P_pin),
   .IO_DataOUT2_N_pin   (IO_DataOUT2_N_pin)
);

parameter PERIOD = 20;

initial begin
  RST_pin = 0;
end

initial begin
  ChipID0 = 0;
end

initial begin
  ChipID1 = 0;
end

initial begin
  ChipID2 = 0;
end
    
initial begin
  IO_DataIN_N_pin = 1'b0;
  #(PERIOD/2);
  forever
    #(PERIOD/2) IO_DataIN_N_pin = ~IO_DataIN_N_pin;
end

initial begin
  IO_DataIN_P_pin = 1'b1;
  #(PERIOD/2);
  forever
    #(PERIOD/2) IO_DataIN_P_pin = ~IO_DataIN_P_pin;
end

//IO_DataIN_CLK_P_pin   
initial begin
  IO_DataIN_CLK_P_pin = 0;
  #240;
//////////////////////////////////////
//1st command
//////////////////////////////////////
  //field 1
    IO_DataIN_CLK_P_pin = 1;
  #20;
    IO_DataIN_CLK_P_pin = 0;
  #20;
    IO_DataIN_CLK_P_pin = 1;
  #20;
    IO_DataIN_CLK_P_pin = 1;
  #20;
    IO_DataIN_CLK_P_pin = 0;
  //field 2
  #20;
    IO_DataIN_CLK_P_pin = 1;
  #20;
    IO_DataIN_CLK_P_pin = 0;    
  #20;
    IO_DataIN_CLK_P_pin = 0;       
  #20;
    IO_DataIN_CLK_P_pin = 0;   
  //field 3
  #20;
    IO_DataIN_CLK_P_pin = 0;
  #20;
    IO_DataIN_CLK_P_pin = 0;    
  #20;
    IO_DataIN_CLK_P_pin = 1;       
  #20;
    IO_DataIN_CLK_P_pin = 0;   
  //field 4
  #20;
    IO_DataIN_CLK_P_pin = 1;
  #20;
    IO_DataIN_CLK_P_pin = 0;    
  #20;
    IO_DataIN_CLK_P_pin = 0;       
  #20;
    IO_DataIN_CLK_P_pin = 0;   
  //field 5
  #20;
    IO_DataIN_CLK_P_pin = 0;       
  #20;
    IO_DataIN_CLK_P_pin = 0;   
  #20;
    IO_DataIN_CLK_P_pin = 0;
  #20;
    IO_DataIN_CLK_P_pin = 0;    
  #20;
    IO_DataIN_CLK_P_pin = 1;       
  #20;
    IO_DataIN_CLK_P_pin = 1;  
  //field 6
  #20;
    IO_DataIN_CLK_P_pin = 0;       
  #20;
    IO_DataIN_CLK_P_pin = 1;   
  #20;
    IO_DataIN_CLK_P_pin = 1;
  #20;
    IO_DataIN_CLK_P_pin = 1;    
  #20;
    IO_DataIN_CLK_P_pin = 1;       
  #20;
    IO_DataIN_CLK_P_pin = 1;   
  #20;
    IO_DataIN_CLK_P_pin = 0;
  #20;
    IO_DataIN_CLK_P_pin = 0;    
  #20;
    IO_DataIN_CLK_P_pin = 0;       
  #20;
    IO_DataIN_CLK_P_pin = 1;   
  #20;
    IO_DataIN_CLK_P_pin = 1;       
  #20;
    IO_DataIN_CLK_P_pin = 1;   
  #20;
    IO_DataIN_CLK_P_pin = 1;
  #20;
    IO_DataIN_CLK_P_pin = 1;    
  #20;
    IO_DataIN_CLK_P_pin = 0;       
  #20;
    IO_DataIN_CLK_P_pin = 0;  

//////////////////////////////////////
//2nd command
////////////////////////////////////// 
    #200;
   //field 1
      IO_DataIN_CLK_P_pin = 1;
   #20;
      IO_DataIN_CLK_P_pin = 0;
   #20;
      IO_DataIN_CLK_P_pin = 1;
   #20;
      IO_DataIN_CLK_P_pin = 1;
   #20;
      IO_DataIN_CLK_P_pin = 0;
   //field 2
   #20;
      IO_DataIN_CLK_P_pin = 1;
   #20;
      IO_DataIN_CLK_P_pin = 0;    
   #20;
      IO_DataIN_CLK_P_pin = 0;       
   #20;
      IO_DataIN_CLK_P_pin = 0;   
   //field 3
   #20;
      IO_DataIN_CLK_P_pin = 0;
   #20;
      IO_DataIN_CLK_P_pin = 0;    
   #20;
      IO_DataIN_CLK_P_pin = 0;       
   #20;
      IO_DataIN_CLK_P_pin = 1;   
   //field 4
   #20;
      IO_DataIN_CLK_P_pin = 0;
   #20;
      IO_DataIN_CLK_P_pin = 0;    
   #20;
      IO_DataIN_CLK_P_pin = 0;       
   #20;
      IO_DataIN_CLK_P_pin = 0;   
   //field 5
   #20;
      IO_DataIN_CLK_P_pin = 0;       
   #20;
      IO_DataIN_CLK_P_pin = 0;   
   #20;
      IO_DataIN_CLK_P_pin = 0;
   #20;
      IO_DataIN_CLK_P_pin = 0;    
   #20;
      IO_DataIN_CLK_P_pin = 1;       
   #20;
      IO_DataIN_CLK_P_pin = 1;  
end  

assign IO_DataIN_CLK_N_pin = !IO_DataIN_CLK_P_pin;

endmodule // FEI4_A_top_tb


