//
// Test Bench Module FEI4_A_lib.FEI4_A_top_WrRdReg_tb.FEI4_A_top_tester
//
// Created:
//          by - Laura.UNKNOWN (SILAB51)
//          at - 11:49:49 01/18/2010
//
// Generated by Mentor Graphics' HDL Designer(TM) 2008.1b (Build 7)
//
`resetall
`timescale 1ns/10ps

module FEI4_A_top_WrRdReg_tb;

// Local declarations

// Internal signal declarations
reg       IO_DataIN_CLK_N_pin;
reg       IO_DataIN_CLK_P_pin;
//reg [2:0] ChipId;
//reg       Ext_Trigger;
reg       DCI;
//reg       reset;
wire      data_out;


FEI4_A_top U_0(
   .IO_DataIN_CLK_N_pin (IO_DataIN_CLK_N_pin),
   .IO_DataIN_CLK_P_pin (IO_DataIN_CLK_P_pin),
//   .ChipId      (ChipId),
//   .Ext_Trigger (Ext_Trigger),
   .DCI         (DCI),
//   .reset       (reset),
   .data_out    (data_out)
);


//ChipId
//initial begin
//  ChipId = 0;
//end

//Ext_Trigger
//initial begin
//  Ext_Trigger = 0;
//end

//CK
parameter PERIOD = 20;

initial begin
  IO_DataIN_CLK_N_pin = 1'b0;
  #(PERIOD/2);
  forever
    #(PERIOD/2) IO_DataIN_CLK_N_pin = ~IO_DataIN_CLK_N_pin;
end

initial begin
  IO_DataIN_CLK_P_pin = 1'b1;
  #(PERIOD/2);
  forever
    #(PERIOD/2) IO_DataIN_CLK_P_pin = ~IO_DataIN_CLK_P_pin;
end

//reset
//initial begin
//  reset = 1;
//  #160;
//  reset = 0;
//  #60;
//  reset = 1;
//end

//reset


//DCI    
initial begin
  #240;
//////////////////////////////////////
//1st command
//////////////////////////////////////
  //field 1
  DCI = 1;
  #20;
  DCI = 0;
  #20;
  DCI = 1;
  #20;
  DCI = 1;
  #20;
  DCI = 0;
  //field 2
  #20;
  DCI = 1;
  #20;
  DCI = 0;    
  #20;
  DCI = 0;       
  #20;
  DCI = 0;   
  //field 3
  #20;
  DCI = 0;
  #20;
  DCI = 0;    
  #20;
  DCI = 1;       
  #20;
  DCI = 0;   
  //field 4
  #20;
  DCI = 0;
  #20;
  DCI = 0;    
  #20;
  DCI = 0;       
  #20;
  DCI = 0;   
  //field 5
  #20;
  DCI = 0;       
  #20;
  DCI = 0;   
  #20;
  DCI = 0;
  #20;
  DCI = 0;    
  #20;
  DCI = 1;       
  #20;
  DCI = 1;  
  //field 6
  #20;
  DCI = 0;       
  #20;
  DCI = 0;   
  #20;
  DCI = 0;
  #20;
  DCI = 1;    
  #20;
  DCI = 1;       
  #20;
  DCI = 0;   
  #20;
  DCI = 0;
  #20;
  DCI = 0;    
  #20;
  DCI = 1;       
  #20;
  DCI = 1;   
  #20;
  DCI = 1;       
  #20;
  DCI = 0;   
  #20;
  DCI = 1;
  #20;
  DCI = 0;    
  #20;
  DCI = 1;       
  #20;
  DCI = 0;  

//////////////////////////////////////
//2nd command
////////////////////////////////////// 
    #200;
   //field 1
   DCI = 1;
   #20;
   DCI = 0;
   #20;
   DCI = 1;
   #20;
   DCI = 1;
   #20;
   DCI = 0;
   //field 2
   #20;
   DCI = 1;
   #20;
   DCI = 0;    
   #20;
   DCI = 0;       
   #20;
   DCI = 0;   
   //field 3
   #20;
   DCI = 0;
   #20;
   DCI = 0;    
   #20;
   DCI = 0;       
   #20;
   DCI = 1;   
   //field 4
   #20;
   DCI = 0;
   #20;
   DCI = 0;    
   #20;
   DCI = 0;       
   #20;
   DCI = 0;   
   //field 5
   #20;
   DCI = 0;       
   #20;
   DCI = 0;   
   #20;
   DCI = 0;
   #20;
   DCI = 0;    
   #20;
   DCI = 1;       
   #20;
   DCI = 1;  
  
end  





endmodule // FEI4_A_top_WrRdReg_tb


